id: P488C5B5F
initial_creation_type: input
source_metadata:
  title: Three Deities of Long Life
  language: en
  description: 'Texts related to the Three Deities of Long Life (tshe lha rnam gsum),
    i.e., Amitāyus (tshe dpag med), White Tārā (sgrol dkar) and Uṣṇīṣayavijayā (rnam
    rgyal ma):'
  volume:
    9307a44a952b47559d772ac1d0095279:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
created_at: '2022-03-01T06:20:43.912875'
last_modified_at: '2022-03-01T06:20:43.912881'
